import FilterLicenses from '@/components/home/FilterLicenses'
import ModelGrid from '@/components/home/ModelGrid'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='grid grid-cols-6 gap-12'>
          <div className='col-span-1 pl-10 h-full min-h-screen bg-violet-50 py-16' id="sidebar">
            <FilterLicenses />
          </div>
          <div className='col-span-5 py-16 pr-10'>
            <div className="flex justify-between">
              <h1>Models</h1>
            </div>
            <ModelGrid />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
